### ISSUE TITLE
java.lang.IllegalStateException: Failed to stop the muxer

### ISSUE THREAD

**Issue by Miteshmakwana73** [deepmedia/Transcoder#139]
I am using Motorola one fusion+ mobile

getting this error

![image](https://user-images.githubusercontent.com/38969602/114543465-de06e580-9c76-11eb-8f19-9bcdaea7acaa.png)

`
2021-04-13 16:36:56.479 20572-21716/com.otaliastudios.transcoder.demo E/TranscodeEngine: Unexpected error while transcoding.
    java.lang.IllegalStateException: Failed to stop the muxer
        at android.media.MediaMuxer.nativeStop(Native Method)
        at android.media.MediaMuxer.stop(MediaMuxer.java:466)
        at com.otaliastudios.transcoder.sink.DefaultDataSink.stop(DefaultDataSink.java:218)
        at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.transcode(DefaultTranscodeEngine.kt:132)
        at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine$Companion.transcode(TranscodeEngine.kt:48)
        at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine.transcode(Unknown Source:2)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:102)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:99)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2021-04-13 16:36:56.479 20572-21716/com.otaliastudios.transcoder.demo I/Decoder(VIDEO,3): release(): releasing codec. dequeuedInputs=0 dequeuedOutputs=0
2021-04-13 16:36:56.479 20572-21716/com.otaliastudios.transcoder.demo E/MediaMuxer: stop() is called in invalid state 3
2021-04-13 16:36:56.486 20572-21716/com.otaliastudios.transcoder.demo W/DefaultDataSink: Failed to release the muxer.
    java.lang.IllegalStateException: Failed to stop the muxer
        at android.media.MediaMuxer.nativeStop(Native Method)
        at android.media.MediaMuxer.stop(MediaMuxer.java:466)
        at android.media.MediaMuxer.release(MediaMuxer.java:706)
        at com.otaliastudios.transcoder.sink.DefaultDataSink.release(DefaultDataSink.java:224)
        at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.cleanup(DefaultTranscodeEngine.kt:137)
        at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine$Companion.transcode(TranscodeEngine.kt:63)
        at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine.transcode(Unknown Source:2)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:102)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:99)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2021-04-13 16:36:56.486 20572-21716/com.otaliastudios.transcoder.demo I/DataSources: release(): releasing...
2021-04-13 16:36:56.487 20572-21716/com.otaliastudios.transcoder.demo I/DefaultDataSource(3): deinitialize(): deinitializing...
2021-04-13 16:36:56.489 20572-21716/com.otaliastudios.transcoder.demo I/DataSources: release(): released.
2021-04-13 16:36:56.490 20572-21716/com.otaliastudios.transcoder.demo I/MediaCodec: (0x7acca6c000) release
2021-04-13 16:36:56.502 20572-21716/com.otaliastudios.transcoder.demo I/MediaCodec: (0x7acfbd8a00) release

`

**Comment by phixtalk** [comment]
Hello, Please were you able to resolve this error?
I'm getting the same error on the emulator.

**Comment by aparkertg** [comment]
Same problem. Not getting caught in onTranscodeProgress, onTranscodeCompleted, onTranscodeCanceled, nor onTranscodeFailed.

This is happening on multiple devices. We will have to try and revert to previous releases or a new library.

Additionally getting this error:

W/DefaultDataSource(1): Could not release extractor:
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaExtractor.release()' on a null object reference
        at com.otaliastudios.transcoder.source.DefaultDataSource.deinitialize(DefaultDataSource.java:95)
        at com.otaliastudios.transcoder.source.FilePathDataSource.deinitialize(FilePathDataSource.java:48)
        at com.otaliastudios.transcoder.internal.DataSources.deinit(DataSources.kt:23)
        at com.otaliastudios.transcoder.internal.DataSources.release(DataSources.kt:67)
        at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.cleanup(DefaultTranscodeEngine.kt:138)
        at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine$Companion.transcode(TranscodeEngine.kt:63)
        at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine.transcode(Unknown Source:2)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:102)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:99)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
    Could not release metadata:
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaMetadataRetriever.release()' on a null object reference
        at com.otaliastudios.transcoder.source.DefaultDataSource.deinitialize(DefaultDataSource.java:100)
        at com.otaliastudios.transcoder.source.FilePathDataSource.deinitialize(FilePathDataSource.java:48)
        at com.otaliastudios.transcoder.internal.DataSources.deinit(DataSources.kt:23)
        at com.otaliastudios.transcoder.internal.DataSources.release(DataSources.kt:67)
        at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.cleanup(DefaultTranscodeEngine.kt:138)
        at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine$Companion.transcode(TranscodeEngine.kt:63)
        at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine.transcode(Unknown Source:2)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:102)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:99)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
I/DefaultDataSource(0): deinitialize(): deinitializing...

Please help.

**Comment by aparkertg** [comment]
Note - Reverted back to version 0.9.1 and it's working as before.

**Comment by muhammedyalcin** [comment]
After migrating from 0.9.1 to 0.10.3, this error started to occur.

**Comment by Noloxs** [comment]
I can also confirm this issue, starting from v0.10.0 to v0.10.4

It seems to be very depended on the device, as I have multiple devices across different Android versions reporting the error and equally many devices which doesn't experience the issue.

So far we have seen the issue on the following devices:
- Motorola G6 Play (Android 9)
- Samsung Galaxy Tab S2 (Android 7)
- Huawei Honor 9  (Android 9)
- Samsung Galaxy S8 (Android 9)
- Samsung Galaxy S9 (Android 10)
- Sony XZ1 Compact (Android 9)
- Motorola G8 Plus (Android 10)
- LG G6 (Android 9)
- Samsung Galaxy S8+ (Android 9)
- Xiaomi Pocophone F1 (Android 10)
- Xiaomi Mi 9 SE
- SHARP QUALCOMM SHV39
- Motorola One Action (Android 10)
- LG G7 ThinQ (Android 10)
- Nokia 6 (Android 9)

**Comment by davindersidhu0770** [comment]
Same Error ... Any update on this?

**Comment by natario1** [comment]
It's not being worked on. Stack traces in this ticket seem to represent different bugs, and in both cases I can't reproduce so it's hard to understand what's wrong.

If you have a repro device and media file, I encourage you to work on it or at least add a failing test here: https://github.com/natario1/Transcoder/blob/main/lib/src/androidTest/java/com/otaliastudios/transcoder/integration/IssuesTests.kt#L67-L90 , add media file in the assets folder. Then we should be able to fix it.

**Comment by davindersidhu0770** [comment]
@natario1 on my device i am getting this exception (java.lang.IllegalStateException: Failed to stop the muxer). working fine of android 7,8,9 or 10 but in 6.0.1 its a bug.

**Comment by jumperson** [comment]
I am also getting the same issue.
I fixed by #159.

**Comment by mycohbasilan** [comment]
Could you try adding `TrackType` to your `DataSource`?

**Comment by anyuta1166** [comment]
The same issue on Xiaomi Redmi Note 9 Pro (Android 10). Reproducible with any file.

```
09-10 20:56:23.030 E/TranscodeEngine(10146): Unexpected error while transcoding.
09-10 20:56:23.030 E/TranscodeEngine(10146): java.lang.IllegalStateException: Failed to stop the muxer
09-10 20:56:23.030 E/TranscodeEngine(10146): 	at android.media.MediaMuxer.nativeStop(Native Method)
09-10 20:56:23.030 E/TranscodeEngine(10146): 	at android.media.MediaMuxer.stop(MediaMuxer.java:466)
09-10 20:56:23.030 E/TranscodeEngine(10146): 	at com.otaliastudios.transcoder.sink.DefaultDataSink.stop(DefaultDataSink.java:218)
09-10 20:56:23.030 E/TranscodeEngine(10146): 	at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.transcode(DefaultTranscodeEngine.kt:132)
09-10 20:56:23.030 E/TranscodeEngine(10146): 	at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine$Companion.transcode(TranscodeEngine.kt:48)
09-10 20:56:23.030 E/TranscodeEngine(10146): 	at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine.transcode(Unknown Source:2)
09-10 20:56:23.030 E/TranscodeEngine(10146): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:102)
09-10 20:56:23.030 E/TranscodeEngine(10146): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:99)
09-10 20:56:23.030 E/TranscodeEngine(10146): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-10 20:56:23.030 E/TranscodeEngine(10146): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-10 20:56:23.030 E/TranscodeEngine(10146): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-10 20:56:23.030 E/TranscodeEngine(10146): 	at java.lang.Thread.run(Thread.java:919)
09-10 20:56:23.031 I/Decoder(VIDEO,4)(10146): release(): releasing codec. dequeuedInputs=0 dequeuedOutputs=0
09-10 20:56:23.031 E/MediaMuxer(10146): stop() is called in invalid state 3
09-10 20:56:23.032 W/DefaultDataSink(10146): Failed to release the muxer.
09-10 20:56:23.032 W/DefaultDataSink(10146): java.lang.IllegalStateException: Failed to stop the muxer
09-10 20:56:23.032 W/DefaultDataSink(10146): 	at android.media.MediaMuxer.nativeStop(Native Method)
09-10 20:56:23.032 W/DefaultDataSink(10146): 	at android.media.MediaMuxer.stop(MediaMuxer.java:466)
09-10 20:56:23.032 W/DefaultDataSink(10146): 	at android.media.MediaMuxer.release(MediaMuxer.java:706)
09-10 20:56:23.032 W/DefaultDataSink(10146): 	at com.otaliastudios.transcoder.sink.DefaultDataSink.release(DefaultDataSink.java:224)
09-10 20:56:23.032 W/DefaultDataSink(10146): 	at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.cleanup(DefaultTranscodeEngine.kt:137)
09-10 20:56:23.032 W/DefaultDataSink(10146): 	at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine$Companion.transcode(TranscodeEngine.kt:63)
09-10 20:56:23.032 W/DefaultDataSink(10146): 	at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine.transcode(Unknown Source:2)
09-10 20:56:23.032 W/DefaultDataSink(10146): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:102)
09-10 20:56:23.032 W/DefaultDataSink(10146): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:99)
09-10 20:56:23.032 W/DefaultDataSink(10146): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-10 20:56:23.032 W/DefaultDataSink(10146): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-10 20:56:23.032 W/DefaultDataSink(10146): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-10 20:56:23.032 W/DefaultDataSink(10146): 	at java.lang.Thread.run(Thread.java:919)
```

**Comment by mohsin-whizpool** [comment]
Same issue on samsung a20s

**Comment by licaon-kter** [comment]
Still an issue on 0.10.5 hence  stuck with 0.9.1, [Huawei P10 Lite](https://www.gsmarena.com/huawei_p10_lite-8598.php) Android 8

**Comment by natario1** [comment]
(Pasted to all my answers today: it's been a long time since my last issues review. I am sorry about the delay and I know you likely have moved on by now. Still, I'm going to answer where I can)

Let's track these "something's broken" issues in #138.
